packages:
  - tiktik-backend
allowBuilds:
  core-js: false
  es5-ext: false
  esbuild: true
  sharp: false
  uglifyjs-webpack-plugin: false
  unrs-resolver: true
overrides:
  '@types/react': 19.3.0
  '@types/react-dom': 19.3.0
